In [4]:
import numpy as np

In [2]:
lis = [[1,2,3],[2,3,4],[4,5,6]]
arr = np.array(lis)
arr

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [3]:
lis = [[1,2,7],[2,6,4],[9,5,6]]
arr1 = np.array(lis)
arr

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [5]:
#normal index based calculation
arr1 + arr

array([[ 2,  4, 10],
       [ 4,  9,  8],
       [13, 10, 12]])

In [6]:
arr1 - arr

array([[0, 0, 4],
       [0, 3, 0],
       [5, 0, 0]])

In [7]:
#matrix multiplication


In [8]:
arr1 @ arr

array([[33, 43, 53],
       [30, 42, 54],
       [43, 63, 83]])

In [9]:
arr1 / 0

/tmp/ipykernel_4098/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [23]:
a = np.array([[1,2,3]])

In [24]:
arr + a

array([[2, 4, 6],
       [3, 5, 7],
       [5, 7, 9]])

In [25]:
a.T

array([[1],
       [2],
       [3]])

In [26]:
a.T

array([[1],
       [2],
       [3]])

In [27]:
arr + a.T

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [29]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ],
       [2.        , 2.23606798, 2.44948974]])

In [30]:
np.log10(arr)

array([[0.        , 0.30103   , 0.47712125],
       [0.30103   , 0.47712125, 0.60205999],
       [0.60205999, 0.69897   , 0.77815125]])

In [31]:
np.exp(arr)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [  7.3890561 ,  20.08553692,  54.59815003],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [33]:
np.min(arr)

1

In [34]:
np.max(arr)

6

In [35]:
arr.flatten()  #reduce higher dimension to 1d

array([1, 2, 3, 2, 3, 4, 4, 5, 6])

In [37]:
np.expand_dims(arr,0)

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [41]:
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [42]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [43]:
np.sum(arr)

27

In [44]:
np.sum(arr, axis = 0)  #sum rowwise

array([ 6,  9, 12])

In [47]:
np.sum(arr,axis = 1)   # sum columnwise(adding columns)

array([ 6, 15,  6])

In [50]:
arr1= np.expand_dims(arr,axis = 0)
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]]])

In [51]:
arr1.shape

(1, 3, 3)

In [52]:
arr1 = np.expand_dims(arr,axis = 0)

In [53]:
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]]])

In [54]:
arr1.shape

(1, 3, 3)

In [55]:
arr1= np.expand_dims(arr,axis = 1)
arr1

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[1, 2, 3]]])

In [5]:
data = np.array([[1,2,3]])

In [6]:
data


array([[1, 2, 3]])

In [7]:
a  = np.squeeze(data)

In [8]:
a

array([1, 2, 3])

In [9]:
data

array([[1, 2, 3]])

In [12]:
a1= np.repeat(data,4)
a1

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [18]:
data = ([1,2],[3,4])
np.repeat(data,2,axis = 1)


array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [19]:
np.repeat(data,2 , axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [20]:
data

([1, 2], [3, 4])

In [21]:
data1=np.array([[1,2,3,4]])
data1

array([[1, 2, 3, 4]])

In [22]:
np.roll(data1,1)

array([[4, 1, 2, 3]])

In [24]:
np.roll(data1,2)

array([[3, 4, 1, 2]])

In [26]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
np.roll(data1,-2)

array([[3, 4, 1, 2]])

In [28]:
data3d = np.array([[[1,2],[3,4],[5,6]]])

In [29]:
data3d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [34]:
np.roll(data3d, 2, axis=1)

array([[[3, 4],
        [5, 6],
        [1, 2]]])

In [35]:
#binary operation on array

In [36]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [37]:
arr1

array([[4, 5, 1, 7],
       [4, 5, 3, 1],
       [1, 7, 7, 3]])

In [38]:
arr2

array([[3, 3, 4, 6],
       [5, 2, 4, 3],
       [6, 5, 5, 4]])

In [39]:
arr1+arr2

array([[ 7,  8,  5, 13],
       [ 9,  7,  7,  4],
       [ 7, 12, 12,  7]])

In [40]:
arr1*arr2

array([[12, 15,  4, 42],
       [20, 10, 12,  3],
       [ 6, 35, 35, 12]])

In [41]:
arr1/arr2

array([[1.33333333, 1.66666667, 0.25      , 1.16666667],
       [0.8       , 2.5       , 0.75      , 0.33333333],
       [0.16666667, 1.4       , 1.4       , 0.75      ]])

In [42]:
arr1-arr2

array([[ 1,  2, -3,  1],
       [-1,  3, -1, -2],
       [-5,  2,  2, -1]])

In [43]:
arr1**2

array([[16, 25,  1, 49],
       [16, 25,  9,  1],
       [ 1, 49, 49,  9]])

In [44]:
arr1>arr2

array([[ True,  True, False,  True],
       [False,  True, False, False],
       [False,  True,  True, False]])

In [45]:
~arr1

array([[-5, -6, -2, -8],
       [-5, -6, -4, -2],
       [-2, -8, -8, -4]])

In [46]:
arr1**arr2

array([[    64,    125,      1, 117649],
       [  1024,     25,     81,      1],
       [     1,  16807,  16807,     81]])

In [47]:
#Numpy string function

In [51]:
arr = np.array(["pw","Skills"])

In [52]:
arr

array(['pw', 'Skills'], dtype='<U6')

In [53]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [54]:
np.char.lower(arr)

array(['pw', 'skills'], dtype='<U6')

In [55]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [57]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [58]:
#Mathematical function
arr1

array([[4, 5, 1, 7],
       [4, 5, 3, 1],
       [1, 7, 7, 3]])

In [59]:
np.sin(arr1)

array([[-0.7568025 , -0.95892427,  0.84147098,  0.6569866 ],
       [-0.7568025 , -0.95892427,  0.14112001,  0.84147098],
       [ 0.84147098,  0.6569866 ,  0.6569866 ,  0.14112001]])

In [60]:
np.cos(arr1)

array([[-0.65364362,  0.28366219,  0.54030231,  0.75390225],
       [-0.65364362,  0.28366219, -0.9899925 ,  0.54030231],
       [ 0.54030231,  0.75390225,  0.75390225, -0.9899925 ]])

In [61]:
np.tan(arr1)

array([[ 1.15782128, -3.38051501,  1.55740772,  0.87144798],
       [ 1.15782128, -3.38051501, -0.14254654,  1.55740772],
       [ 1.55740772,  0.87144798,  0.87144798, -0.14254654]])

In [62]:
np.log10(arr1)

array([[0.60205999, 0.69897   , 0.        , 0.84509804],
       [0.60205999, 0.69897   , 0.47712125, 0.        ],
       [0.        , 0.84509804, 0.84509804, 0.47712125]])

In [63]:
np.exp(arr1)

array([[  54.59815003,  148.4131591 ,    2.71828183, 1096.63315843],
       [  54.59815003,  148.4131591 ,   20.08553692,    2.71828183],
       [   2.71828183, 1096.63315843, 1096.63315843,   20.08553692]])

In [64]:
np.power(arr1,4)

array([[ 256,  625,    1, 2401],
       [ 256,  625,   81,    1],
       [   1, 2401, 2401,   81]], dtype=int32)

In [65]:
np.mean(arr1)

4.0

In [66]:
np.max(arr1)

7

In [68]:
np.std(arr1) #standrd deviation

2.1984843263788196

In [69]:
np.subtract(arr1,arr2)

array([[ 1,  2, -3,  1],
       [-1,  3, -1, -2],
       [-5,  2,  2, -1]])

In [70]:
np.add(arr1,arr2)

array([[ 7,  8,  5, 13],
       [ 9,  7,  7,  4],
       [ 7, 12, 12,  7]])

In [71]:
np.multiply(arr1,arr2)

array([[12, 15,  4, 42],
       [20, 10, 12,  3],
       [ 6, 35, 35, 12]])

In [72]:
np.mod(arr1,arr2)

array([[1, 2, 1, 1],
       [4, 1, 3, 1],
       [1, 2, 2, 3]])

In [73]:
np.power(arr1,arr2)

array([[    64,    125,      1, 117649],
       [  1024,     25,     81,      1],
       [     1,  16807,  16807,     81]])

In [75]:
np.sqrt(arr1)

array([[2.        , 2.23606798, 1.        , 2.64575131],
       [2.        , 2.23606798, 1.73205081, 1.        ],
       [1.        , 2.64575131, 2.64575131, 1.73205081]])

In [76]:
#sort and search

In [77]:
arr = np.array([5,6,1,2])

In [78]:
np.sort(arr)

array([1, 2, 5, 6])

In [79]:
np.searchsorted(arr,3)

4

In [80]:
arr1 = np.array([0,1,2,3,0,5,0])

In [81]:
np.count_nonzero(arr1)

4

In [82]:
arr1>0

array([False,  True,  True,  True, False,  True, False])

In [83]:
np.where(arr1>0)

(array([1, 2, 3, 5], dtype=int64),)

In [84]:
np.extract(arr1 > 0 ,arr1)

array([1, 2, 3, 5])

In [85]:
arr1

array([0, 1, 2, 3, 0, 5, 0])

In [86]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 83886080,
              0])

In [87]:
import numpy.matlib as nm

In [89]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [90]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [91]:
#Numpy linear algebra

In [95]:
arr1 = np.array([[2,3],[4,5]])
arr2 = np.array([[1,3],[4,5]])

In [96]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [104]:
a = np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [98]:
b = np.array([16,-8,0])

In [99]:
a

array([[ 7, -5, -3],
       [ 2, -5,  2],
       [ 5,  3, -7]])

In [100]:
b

array([16, -8,  0])

In [110]:
np.linalg.solve(a,b) #linear equation solution

array([1., 3., 2.])

In [108]:
np.linalg.det(arr1)  #determinant of matrix

-2.0

In [109]:
np.linalg.inv(arr1)  #inverse of matrix

array([[-2.5,  1.5],
       [ 2. , -1. ]])