In [1]:
import numpy as np


In [2]:
#1. What is a Python library? Why do we use Python libraries?
#sol:- Python library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations. Other than pre-compiled codes, a library may contain documentation, configuration data, message templates, classes, and values, etc.
# we use python library as it makes Python programming easier and simpler

In [3]:
#2. What is the difference between Numpy array and List?
#sol:-NumPy arrays can only contain elements of the same data type. This allows for more efficient storage and operations.
#Lists can contain elements of different data types, making them more flexible but potentially less efficient for numerical operations.
#NumPy arrays are more efficient for numerical operations because they are implemented in C and have a fixed, homogeneous data type.
#Lists are more flexible but may be slower for numerical operations, especially with large datasets

In [12]:
#3. Find the shape, size and dimension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
shape = a.shape
size = a.size
dim = a.ndim
print(f" shape = {shape}, size = {size}, dim = {dim}")

 shape = (3, 4), size = 12, dim = 2


In [14]:
#4. Write python code to access the first row of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
print(a[0])

[1 2 3 4]


In [18]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
#sol:- to access the element we mention its column and row and run the command
a[2][3]

12

In [22]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
print(a[:, 1::2]) 

[[ 2  4]
 [ 6  8]
 [10 12]]


In [26]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
import random 
print(np.random.rand(3,3))

[[0.33374685 0.45212549 0.51590514]
 [0.87351957 0.37484808 0.4006001 ]
 [0.82276892 0.41515469 0.1147491 ]]


In [27]:
#8. Describe the difference between np.random.rand and np.random.randn?
#sol:-np.random.rand = This function generates random numbers from a uniform distribution over the interval [0, 1).
#The returned values are in the half-open interval [0, 1), meaning 0 is included, but 1 is excluded.
#whearas, np.random.randn = This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
#The returned values are not bounded within a specific range and can be positive or negative

In [35]:
#9. Write code to increase the dimension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8]
#[9, 10, 11, 12]]
old_dim = a.ndim
print(f"old_dim = {old_dim}")
new_dim = a[:,:,np.newaxis]
print(f" new_dim = {new_dim.ndim}")


old_dim = 2
 new_dim = 3


In [37]:
#10. How to transpose the following array in NumPy?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
print(f"transpose = {a.T}")

transpose = [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [49]:
#11. Consider the following matrix:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
#Perform the following operation using Python1
#1 Index wise multiplication
#2 Matrix multiplication
#3 Add both the matrics
#4 Subtract matarix B from A
#5 Divide Matrix B by A
print(f"index wise multiplication : {A*5},and {B*7}")
print(f"matrix multiplication cannot be performed as first matrix column is not equal to second matrix row")
print(f"addition: {A+B}")
print(f"subratction : {A-B}")
print(f"division: {B/A}")

index wise multiplication : [[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]],and [[ 7 14 21 28]
 [35 42 49 56]
 [63 70 77 84]]
matrix multiplication cannot be performed as first matrix column is not equal to second matrix row
addition: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
subratction : [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
division: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [50]:
#12.  Which function in Numpy can be used to swap the byte order of an array?
#sol: In NumPy, the function ""numpy.ndarray.byteswap"" can be used to swap the byte order of an array.

In [51]:
#13.  What is the significance of the np.linalg.inv function?
#sol: The ""np.linalg.inv"" function in NumPy is used to compute the multiplicative inverse or simply the inverse of a square matrix.

In [53]:
#14. What does the np.reshape function do, and how is it used?
#sol: The ""np.reshape"" function in NumPy is used to give a new shape to an array without changing its data.
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(original_array, (3, 2))
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#15. What is broadcasting in Numpy?