In [1]:
import numpy as np

In [2]:
arr = np.ones((3,4))

In [3]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
 arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [5]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.eye(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [8]:
#optional
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [9]:
#extra topic
import random

In [10]:
random.choice((1,2,3,4,5,6))

1

In [11]:
random.choice('Ajay')

'j'

In [12]:
random.randrange(1,1000)

221

In [13]:
random.random() # a random num betwn 0(included) and 1(excluded)

0.6959549512567035

In [14]:
lis = [1,2,3,4,5]
random.shuffle(lis)
lis

[3, 2, 5, 1, 4]

In [15]:
random.uniform(7,14)   # a num betwn 7 and 14

12.530613244629905

In [16]:
#come back to numpy

In [17]:
np.random.rand(2,3)

array([[0.99225814, 0.71687882, 0.26968635],
       [0.70898375, 0.64344487, 0.13653174]])

In [18]:
np.random.rand(1)

array([0.0046895])

In [19]:
np.random.randn(2,4)

array([[-0.00667065, -0.24742742, -1.19532305, -0.53751369],
       [-0.39850444,  2.07228613, -0.87460337, -0.13411399]])

In [20]:
np.random.random_sample()

0.9600596043027497

In [21]:
np.random.randint(1,5,size = (3,4))

array([[3, 1, 1, 1],
       [1, 4, 1, 4],
       [1, 2, 4, 4]])

In [22]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
(arr.reshape(4,-1))*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [25]:
arr.reshape(12, ).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr.reshape(3,2,2)#3d

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
arr.reshape(1,2,2,3)#4d

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [28]:
arr.reshape(1,1,1,1,1,1,1,1,1,1,1,2,2,3)#n-dimensioanl

array([[[[[[[[[[[[[[1., 1., 1.],
                   [1., 1., 1.]],

                  [[1., 1., 1.],
                   [1., 1., 1.]]]]]]]]]]]]]])

In [29]:
lis = [1,2,3,4]

In [30]:
arr = np.array(lis)
arr

array([1, 2, 3, 4])

In [31]:
arr.ndim

1

In [32]:
arr2 = np.array([[2,3],[4,5]])

In [33]:
arr2

array([[2, 3],
       [4, 5]])

In [34]:
arr3 = np.zeros((1,3,4))  #3 rows, 4 col >> 2d array + 1 extra dimension

In [35]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
arr3.ndim

3

In [37]:
arr4 = np.zeros((1,1,3,4))  #3 rows, 4 col >> 2d array + (1 + 1 )extra dimension

In [38]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [39]:
arr4.ndim

4

In [40]:
arr4.shape

(1, 1, 3, 4)

In [41]:
arr5 = np.zeros((2,3,4))
arr5     #here 2 means repeating 2 times

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
arr5.ndim

3

In [43]:
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[6, 6, 2, 3, 2, 9],
       [9, 9, 5, 1, 3, 4],
       [7, 8, 4, 5, 6, 6],
       [4, 2, 9, 5, 1, 8],
       [4, 3, 5, 4, 7, 8]])

In [44]:
arr1>5

array([[ True,  True, False, False, False,  True],
       [ True,  True, False, False, False, False],
       [ True,  True, False, False,  True,  True],
       [False, False,  True, False, False,  True],
       [False, False, False, False,  True,  True]])

In [45]:
arr1[arr1 > 5] #give all values in array where condition is true

array([6, 6, 9, 9, 9, 7, 8, 6, 6, 9, 8, 7, 8])

In [46]:
arr1[arr1<5]

array([2, 3, 2, 1, 3, 4, 4, 4, 2, 1, 4, 3, 4])

In [47]:
arr

array([1, 2, 3, 4])

In [48]:
arr[0]

1

In [49]:
arr1

array([[6, 6, 2, 3, 2, 9],
       [9, 9, 5, 1, 3, 4],
       [7, 8, 4, 5, 6, 6],
       [4, 2, 9, 5, 1, 8],
       [4, 3, 5, 4, 7, 8]])

In [50]:
arr1[0]

array([6, 6, 2, 3, 2, 9])

In [51]:
arr1[0][0]

6

In [52]:
arr1[0,[1,3]]

array([6, 3])

In [53]:
arr1[2:5]

array([[7, 8, 4, 5, 6, 6],
       [4, 2, 9, 5, 1, 8],
       [4, 3, 5, 4, 7, 8]])

In [54]:
arr1[2:5,[0,2]]

array([[7, 4],
       [4, 9],
       [4, 5]])

In [55]:
arr1[2:5, 1:3]

array([[8, 4],
       [2, 9],
       [3, 5]])

In [56]:
arr1 

array([[6, 6, 2, 3, 2, 9],
       [9, 9, 5, 1, 3, 4],
       [7, 8, 4, 5, 6, 6],
       [4, 2, 9, 5, 1, 8],
       [4, 3, 5, 4, 7, 8]])

In [57]:
arr2

array([[2, 3],
       [4, 5]])

In [58]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [59]:
#matrix multiplication