In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [10]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
type(np.array(l))

numpy.ndarray

In [9]:
arr.ndim

1

In [11]:
l = [1,2,3,4,5,"Rishi"]
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U21')

In [13]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2.ndim

2

In [16]:
l = [1,2,3,4]
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [17]:
np.matrix(arr2)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [19]:
l = [1,2,3,4]
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [20]:
np.matrix([[[1,2],[5,6],[7,8]]])

ValueError: matrix must be 2-dimensional

In [21]:
np.array([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [22]:
np.asarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [23]:
np.asanyarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [27]:
l=[1,2,34]

In [28]:
mat = np.matrix(l)

In [29]:
mat

matrix([[ 1,  2, 34]])

In [30]:
np.asanyarray(mat)

matrix([[ 1,  2, 34]])

In [31]:
t = ([1,2,3],[4,5,6])

In [32]:
np.asanyarray(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a = 5

In [34]:
np.array(a)

array(5)

In [35]:
l = [1,2,3,4,5]
arr= np.array(l)
arr

array([1, 2, 3, 4, 5])

In [36]:
arr[3]

4

In [38]:
a= arr
arr[0] = 1000
arr

array([1000,    2,    3,    4,    5])

In [39]:
a   #shallow copy

array([1000,    2,    3,    4,    5])

In [43]:
b = a.copy()


In [46]:
b[0] = 2000
b               #deep copy

array([2000,    2,    3,    4,    5])

In [47]:
a

array([1000,    2,    3,    4,    5])

In [48]:
#multiple ways to generate arrays

In [51]:
np.fromfunction(lambda i,j : i==j, shape = (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [53]:
arr = np.fromfunction(lambda i,j : i==j, shape = (3,3))
arr.size
arr.shape

(3, 3)

In [58]:
np.fromfunction(lambda i,j : i*j, shape = (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [64]:
iterable = (i*i for i in range(5))
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [62]:
np.fromstring('23 34 67', sep = ' ')

array([23., 34., 67.])

In [63]:
np.fromstring('suhani,Ajay,Anwesha', sep = ',')

/tmp/ipykernel_92/1536880389.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('suhani,Ajay,Anwesha', sep = ',')


array([], dtype=float64)

In [65]:
arr

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [66]:
a

array([1000,    2,    3,    4,    5])

In [67]:
a.shape

(5,)

In [68]:
a.size

5

In [70]:
a.dtype

dtype('int64')

In [71]:
l = [1,2,3,"Ajay"]
arr = np.array(l)
arr.dtype

dtype('<U21')

In [73]:
list(range(1.0,2.10)) # range cnnot deal with float value

TypeError: 'float' object cannot be interpreted as an integer

In [76]:
list(np.arange(0.1,10.2,0.2))

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004,
 2.1000000000000005,
 2.3000000000000007,
 2.5000000000000004,
 2.7000000000000006,
 2.900000000000001,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.7000000000000006,
 3.900000000000001,
 4.1000000000000005,
 4.300000000000001,
 4.500000000000001,
 4.7,
 4.9,
 5.1000000000000005,
 5.300000000000001,
 5.500000000000001,
 5.700000000000001,
 5.9,
 6.1000000000000005,
 6.300000000000001,
 6.500000000000001,
 6.700000000000001,
 6.900000000000001,
 7.100000000000001,
 7.300000000000001,
 7.500000000000001,
 7.700000000000001,
 7.900000000000001,
 8.100000000000001,
 8.3,
 8.500000000000002,
 8.700000000000001,
 8.900000000000002,
 9.100000000000001,
 9.3,
 9.500000000000002,
 9.700000000000001,
 9.900000000000002,
 10.100000000000001]

In [86]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [84]:
np.logspace(1,5 , 10,base =2 )

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [87]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [88]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [93]:
arr3= np.zeros((3,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [94]:
arr3.ndim

3

In [99]:
arr4= np.zeros((2,4,3,4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [100]:
arr4.ndim

4

In [105]:
arr5= np.ones((5,3),int)
arr5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [104]:
arr4 + 6

array([[[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]],


       [[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]]])

In [106]:
arr5 + 8

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])